package com.spectrum.spectrum.src.config

object Constants {

    var APP_TAG = "Spectrum"
    var SCREEN_WIDTH: Int = 0
    var SCREEN_HEIGHT: Int = 0
    var STATUS_BAR_HEIGHT: Int = 0
    var DENSITY: Float = 0f
    const val BASE_URL = "http://spectrum-app.shop:9000"
    const val TOKEN = "spectrum_token"
    const val USER_INDEX = "user_index"
    const val USER_NAME = "user_name"
    const val USER_EMAIL = "user_email"
    const val MEDIA_TYPE_JSON = "application/json;charset=UTF-8"

    const val press_back_one_more = "뒤로가기 한번 더 누르면 종료"
    const val request_failed = "요청을 처리하지 못했습니다"
    const val enter_email = "이메일을 입력하세요"
    const val password = "비밀번호"
    const val enter_password = "비밀번호를 입력해주세요"
    const val enter_password_again = "비밀번호를 한 번 더 입력해주세요"
    const val possible_email = "사용 가능한 계정입니다"
    const val password_updated = "비밀번호 변경이 완료되었습니다"
    const val password_matches = "비밀번호가 일치합니다"
    const val password_error = "영어, 숫자, 특수문자를 조합하여 8자리 이상 입력해주세요"
    const val password_match_error = "비밀번호가 일치하지 않습니다 동일한 비밀번호를 입력해주세요"
    const val enter_nickname = "닉네임을 입력하세요"
    const val nickname_error = "한글, 영어, 숫자만 사용 가능합니다"
    const val nickname_exists = "이미 존재하는 닉네임입니다"
    const val nickname_possible = "사용 가능한 닉네임입니다"
    const val sign_up_complete = "회원가입이 완료되었습니다"
    const val confirm = "확인"
    const val select_age = "연령 선택"
    const val select_your_job_group = "관심 직군을 선택해 주세요"
    const val under_construction = "준비중인 기능입니다."
    const val required_academic_information = "학교 구분과 졸업 여부는 필수 항목입니다"
    const val enter_every_fields = "모든 항목을 입력해주세요"
    const val enter_required_fields = "필수 항목들을 입력해주세요"
    const val enter_appropriate_email = "이메일 형식에 맞게 입력해 주세요"
    const val valid_email = "사용 가능한 이메일입니다"
    const val invalid_email = "이미 가입된 이메일입니다"
    const val available_nickname = "사용 가능한 닉네임입니다"
    const val unavailable_nickname = "이미 존재하는 닉네임입니다"
    const val grade = "학점"
    const val period_error = "입사일은 퇴사일 보다 빨라야 합니다"
    const val free_form_text = "자유 글"
    const val free_form_text_hint = "현재 스펙과 관련하여 고민이나 후기를 적어주세요"
    const val free_advices = "자유 고민"
    const val free_advices_hint = "현재 스펙과 관련하여 고민과 질문을 적어주세요"
    const val free_reviews = "자유 후기"
    const val free_reviews_hint = "자유롭게 취업 후기를 적어주세요"
    const val spec_of = "님의 스펙"
    const val spec_updated = "스펙이 등록되었습니다"
    const val spec_withdrawn = "스펙등록이 취소되었습니다"
    const val post_uploaded = "게시글이 등록되었습니다"
    const val select_your_job_status = "종류를 선택해주세요"
    const val select_category = "주제를 선택해주세요"
    const val please_enter_title = "제목을 입력해주세요"
    const val please_enter_content = "내용을 입력해주세요"
    const val edit = "수정"
    const val delete = "삭제"
    const val ask_delete_spec = "스펙을 삭제하시겠습니까?"
    const val yes = "예"
    const val no = "아니오"
    const val cancel = "취소"
    const val edit_spec = "스펙 수정"
    const val register_spec = "스펙 등록"
    const val ask_delete = "삭제하시겠습니까?"
    const val post_deleted = "게시글이 삭제되었습니다"
    const val post_edited = "게시글이 수정되었습니다"
    const val please_register_spec = "스펙을 등록해주세요"
    const val ask_log_out = "스펙트럼에서 로그아웃 하시곘습니까?"
    const val spec_story = "스펙 이야기"
    const val company = "기업"
    const val comment_uploaded = "반응이 등록되었습니다"
    const val leave_comment = "의견 남기기"
    const val edit_comment = "의견 수정하기"
    const val no_entry = "없음"
    const val company_info = "기업정보"
    const val all = "전체"
    const val spec_count_suffix = "개의 스펙트럼이 쌓여있습니다"

}